
url: https://hdlab.space/
baseurl: "/novedades"

title: Novedades
author: HD LAB CONICET

lang: es

plugins:
  - jekyll-seo-tag

theme: null
color: "#13ccf9"

repository: hdlabconicet/novedades

# disqus:
#   shortname: example-com
#
rrss:
  email: "hdlabconicet@gmail.com"
  facebook: "https://www.facebook.com/HDLAB.CONICET/"
  github: "https://github.com/hdlabconicet"
