
url: https://rominicky.github.io/
baseurl: "/prueba-posthdlab2"

title: Novedades HDLAB CONICET
email: hdlabconicet@gmail.com
author: Romina De León

lang: es

plugins:
  - jekyll-seo-tag

theme: null
color: "#13ccf9"

repository: rominicky/prueba-posthdlab2

# disqus:
#   shortname: example-com
#
rrss:
  email: "hdlabconicet@gmail.com"
  facebook: "https://www.facebook.com/HDLAB.CONICET/"
  github: "https://github.com/hdlabconicet"
